### ISSUE TITLE
macos run example ,not work , tips: connection failed

### ISSUE THREAD

**Issue by huafsud** [starkdmi/flutter_download_manager#2]
hi @starkdmi 
this is a very good project , 
but 
macos run example_complex ,not work , 
tips: connection failed

but ios is ok, 

i don't know this error ,how to fixed?

thank you very much ~

**Comment by starkdmi** [comment]
Hey, @huafsud, macos requires network permissions to be set explicitly - [link](https://developer.apple.com/documentation/xcode/configuring-the-macos-app-sandbox). I'll check later if it is the case.

**Comment by starkdmi** [comment]
Enabling outgoing connections in Xcode resolved an issue for me:
<img width="372" alt="Screenshot 2023-08-23 at 23 07 39" src="https://github.com/starkdmi/flutter_download_manager/assets/21260939/6075f274-4cad-47a6-89a9-81df02d574f6">

**Comment by huafsud** [comment]
@starkdmi  thank you man , you are right ,  thank you very much ~~~
